
name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        working-directory: ${{env.working-dir-backend}}
    - run: npm ci
      working-directory: ${{env.working-dir-backend}}
    - run: npm run test
      working-directory: ${{env.working-dir-backend}}
      env:
        CI: true
        working-dir-backend : ./backend
        working-dir-frontend: ./client